title: Getting started with Mu
hero_image: images/banner.png
description: Find out how to use the Mu code editor
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Installing Mu
- title: Mu modes
- title: Creating code with Mu
- title: Multiple programs
- title: Code checking and debugging
- title: Look and feel
- title: What next?
